name: GitHub metrics
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: Personal metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, activity, repositories"
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_traffic: yes
          plugin_languages: yes
          plugin_languages_ignored: jupyter%20notebook
          plugin_languages_skipped: ''
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14 
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_gists: yes
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_limit: 15
          config_timezone: Africa/Ghana