# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
# https://metrics.lecoq.io
name: Metrics
on:
  # Schedule updates (each month)
  schedule: [{cron: "0 0 1 * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: thehinneh
          template: classic
          base: header, metadata
          config_display: columns
          config_timezone: America/New_York
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_habits_trim: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_sections: most-used
          # plugin_repositories: 100
          plugin_repositories: yes
          plugin_repositories_affiliations: owner
          # plugin_repositories_batch: 100
          plugin_languages_ignored: html, css, scss, SCSS
#           config_padding: 10%
#           plugin_lines: yes
#           plugin_topics: yes
#           plugin_topics_sort: stars
#           plugin_topics_limit: 15
